version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directory: "/examples/default"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
